version: '3.5'
services:
    redis:
        image: redis
        ports:
            - 6379
        networks:
            - host_internal
    elasticsearch:
        image: elasticsearch:6.7.0
        ports:
            - 9200
        networks:
            - host_internal
    nginx:
        build: ./docker/build/nginx
        ports:
            - "80:80"
            - "443:443"
        environment:
            - SERVER_NAME=docker.local
#            - PHP_SERVICE=php #default
#            - PHP_PORT=9000 #default
#            - ROOT_FOLDER=/project #default
#            - IS_HTTPS=false #default
#            - IS_MAGENTO=true #default
#            - IS_MAGENTO_MULTI=false #default
#            - MAGENTO_MODE=production #default
#            - MAGENTO_RUN_TYPE=store #default
        volumes:
            - "./docker/logs/nginx/:/var/log/nginx/"
            - ".:/project:rw"
        depends_on:
            - php
        networks:
            - host_internal
    php:
        build:
            context: ./docker/build/php
            args:
                - VERSION=7.1
        ports:
            - 9000
        environment:
            - IS_ACTIVE_XDEBUG=true
            - XDEBUG_REMOTE_HOST=196.216.0.1
            - ENABLE_SENDMAIL=true
#            - CONFIG=
#                   date.timezone=Asia/Ho_Chi_Minh
            #       config_name2=value2 ...
        volumes:
            - ".:/project:rw"
        depends_on:
            - mariadb
            - redis
            - elasticsearch
        networks:
            - host_internal
    mariadb:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=
            - MYSQL_USER=vothanhdber
            - MYSQL_PASSWORD=vothanH@Pass
            - MYSQL_ROOT_PASSWORD=rooT@Pass
        volumes:
            - ./docker/dbdata:/var/lib/mysql
        networks:
            - host_internal
networks:
    host_internal:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
        ipam:
            driver: default
            config:
                - subnet: 196.216.1.0/16
